### ISSUE TITLE
Problem with deploying to microsoft azure while using pnpm as package manager

### ISSUE THREAD

**Issue by BragdonD** [adaltas/ece-devops-2023-fall#3]
I am encountering a severe difficulty to deploy the web app to microsoft azure, it keeps telling me that dependencies cannot be found...

I try to switch to npm as packet manager but I still get the same problem. 

The only option I found is going into the debug console and run npm install manually there and restart the web app. But at this point it is no more CD, since it requires a human interaction...

Does anyone have an idea of how to solve this? Is it a bug or just I am doing something wrong?

Below are my files:
package.json:
```json
{
  "name": "ece-userapi",
  "version": "1.0.0",
  "description": "User API web application",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "nodemon src/index.js",
    "test": "mocha test/*.test.js"
  },
  "author": "Sergei Kudinov",
  "license": "",
  "dependencies": {
    "body-parser": "^1.20.2",
    "debug": "^4.3.4",
    "express": "^4.17.2",
    "mixme": "^0.5.4",
    "redis": "^3.1.2"
  },
  "devDependencies": {
    "chai": "^4.3.6",
    "chai-http": "^4.3.0",
    "eslint": "^8.9.0",
    "eslint-plugin-mocha": "^10.0.3",
    "mocha": "^9.2.0",
    "nodemon": "^3.0.1"
  },
  "mocha": {
    "timeout": 10000
  }
}
```
azure.yaml:
```yml
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - devops-lab4

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Zip Artifact for deployment job
        run: |
          zip -r node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment job
        run: |
          unzip node-app.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'devops-lab4'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93F1C2FB34404DBEB8BBF656F2E9F859 }}
          package: .
```

CI delivery:
```yml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
      - name: Run Test
        run: npm run test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
```

PS: Those are the files to run npm since I tried npm as last resort...
